version: "3.9"

services:
  bot:
    build: .
    container_name: my_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/app
      - ./credentials.json:/app/credentials.json:ro
